### ISSUE TITLE
Board Voting Issues 2014

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#118]
May not be complete yet.
- [ ] #33: Logos
- [x] #78: Keeping physical records (2 weeks vs. month)
- [x] #81: Mean of 3 for FMC
- [ ] #94: Must have number of cubes for multi
- [x] #105: Change 1/2 multi BLD to DNF
- [x] #111: Recognize Means of 3 for BLD on the WCA website

See #112 for the eventual list of changes.

**Comment by lgarron** [comment]
Closing this issue (the remaining ones are part of the milestone, and everything's documented in #112).
