### ISSUE TITLE
Controversial 2014 Regulation Changes

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/wca-regulations#148]
Based on the ongoing discussions on the Speedsolving Forum. (Somewhat in order of significance.)
- [x] Acceptable tile thickness changing from ≤1.5mm to ≤1.0mm (#166)
- [x] Disallowing puzzles with painted/printer colours (#166)
- [ ] Addition of Mean of 3 for FMC, and removal of Best of 3 for FMC (#109)
- [ ] Retroactive records for FMC Mean of 3 and 3BLD Mean of 3 (#170)
- [x] Disallowing layover stickers for BLD events, but allowing them for non-BLD events (#33)
- [x] DNS for pre-signing attempts (#63)

**Comment by iVinshe** [comment]
After reading a ton of community feedback, here're my thoughts:
- Acceptable tile thickness changing from ≤1.5mm to ≤1.0mm

No change. This is a fairness issue. I have a sneaking suspicion a lot of
"fast" cubers are fast specifically because they're consciously or
unconsciously seeing more of puzzles as well. In addition, Regulations
should be competitor, method, and speed-neutral, as usual.
- Disallowing puzzles with painted/printer colours

Not really sure why this was necessary. I'd be okay either away.
- Addition of Mean of 3 for FMC, and removal of Best of 3 for FMC

I think Best of 3 is a better format specifically for this event, because
of the scarcity of 3-round FMC events, among other reasons.
- Retroactive records for FMC Mean of 3 and 3BLD Mean of 3

Nononononono retroactive records. NO.
- DNF for a score of 1/2 in Multi BLD

No change. As before, I think that 1/2 is not MultiBLD because you didn't
solve multiple cubes correctly.
- Disallowing them for BLD events, but allowing them for non-BLD events

I assume you meant nonsymmetrical puzzles. No change.
- DNS for pre-signing attempts

I forget who suggested it, but I like the idea that if you leave the
station for a non-emergency reason, you accept the result.

**Comment by sarahstrong314** [comment]
My thoughts:
- Acceptable tile thickness changing from ≤1.5mm to ≤1.0mm

This clearly affects a lot of megaminx solvers. I think the change is way too sudden, and many cubers are rightfully upset. I think a long grace period would be ideal -- I suggest 6 or 9 months. (I'm aware that the original grace period of 3 months was revoked). Either that, or change it back to ≤1.5mm.
- Disallowing puzzles with painted/printer colours

Is there any other reason that this was changed, other than for the sake of simplifying the Regulations a bit and making Delegates' duties a bit easier? Kris De Asis gave an example of someone who this would greatly affect, and there are surely others who are also used to using cubes with painted colours, so I don't think this change is worth it. Disallowing them would very likely do more damage to competitors than it helps organizers and Delegates.
- Addition of Mean of 3 for FMC, and removal of Best of 3 for FMC 

I'm in favour of Mean of 3 for FMC being officially recognized. However, I can understand why many people would still prefer the Best of 3 format over the Mean of 3 format for competitions. I'm not an avid FMC competitor, so I can't say which format I like the best, but I suggest doing what make most FMC solvers happy. I think that would involve having official ranks for Means of 3, but have a Best of X format, where X ∈ {1,2,3}, for competitions.
- Retroactive records for FMC Mean of 3 and 3BLD Mean of 3

There are some major cons for both recognizing and not recognizing retroactive records. Either way, many people will be disappointed. I think it's the right decision to recognize them, mainly for the sake of consistency. I don't feel too strongly toward it though, since I don't actively compete in either event.
- Disallowing layover stickers for BLD events, but allowing them for non-BLD events

Just like how stickerless cubes are no longer acceptable for BLD events, I believe there should be consistency between puzzles and puzzle features that are allowed for events. If overlay stickers are no longer allowed for BLD events, they shouldn't be allowed for any event. This should make it much easier for competition organizers and Delegates to determine competition legal puzzles.
- DNS for pre-signing attempts

I like this idea very much. However, I think Delegates should be allowed to give competitors a chance if a competitor mistakingly draws a line down their scorecard (this is a habit for some people, and they might do it without thinking). I think DNS penalties should be given to only competitors who _refuse_ to remove the line they drew. I think this rule should be for the purpose of preventing people from signing future attempts, rather than for punishing those who make mistakes like this.  I like the attitude of "You drew the line, if you don't erase it then you'll get a DNF average" much more than "You drew the line... you just earned a DNF average".

**Comment by iVinshe** [comment]
Re: Retroactive records for FMC Mean of 3 and 3BLD Mean of 3
Okay, I think I probably should've provided some reasoning beyond NOOOO.

In my eyes, adding a new round format is essentially adding a new event. Competitors competed with the expectation that they would be recognized for a "Best of 3" format, and strategized their attempts differently - Best of 3 incentives you to go as fast as you can on each attempt, without regard for how a DNF might affect your average. I agree that the data is there, but I don't think the records should be recognized because they were not set. I don't think this is a good precedent to set. As far as the consistency argument, I don't see where this comes up; I don't think we retroactively recognized records in the past.

In addition, Sebastien's presence and the whole conflict-of-interest can-of-worms this opens up is very troubling. Sebastien, I know you have the ability to take this record anyways.

**Comment by SAuroux** [comment]
Vincent, you are clearly lacking of knowledge then:
- WC82 and WC03 have not even been WCA-competitions. The results were still retroactively recognized and the records were retroactively provided.
- when introducing MBF with an hour as time limit all results that matched the new situation got recognized for the "new" event and records were awarded. The first "real" record in the MBF WR history is Kai Jiptner's 10/10 which is only the 5th WR listed.

So the WCA has always acted this way when data was available. And to me it makes no sense at all to recognize results from the past but to not award them with records. How weird would it be if the #1 results of the world would not be the official WR?

I only see 2 considerable options:

1) Keep it as is (recognize all records from the past)
2) Only award the records that still stood on January 1st, 2014, when the format was introduced.

I am convinced that 1) makes more sense and also prefer this because of consistency. I'd also be fine with 2) though.

Discussion about this is still ongoing within the Board and to make it fully clear: If it comes to a voting, I will abstain, even though my opinion about this has nothing to do with myself holding any kind of record.

**Comment by SAuroux** [comment]
@Sa967St 

> I like the best, but I suggest doing what make most FMC solvers happy. I think that would involve having official ranks for Means of 3, but have a Best of X format, where X ∈ {1,2,3}, for competitions.

This is just so aweful. :( Just like many people on Speedsolving, you seem to just focus on the ranking, which was not the main point of what this comes from, but only a consequence of the format being added. The main point of the proposal has always been the competition format to provide fairer condititions on big competitions (especially when titles are awarded) where a lucky fluke could make you win the event so far, which is just awful, compared to all other events.
Focusing on the ranking totally rapes the intention of the whole proposal...

**Comment by timhabermaas** [comment]
@SAuroux 

> - WC82 and WC03 have not even been WCA-competitions. The results were still retroactively recognized and the records were retroactively provided.
> - when introducing MBF with an hour as time limit all results that matched the new situation got recognized for the "new" event and records were awarded.
- I think it's pretty fair to say these two competitions were exceptions and we added them simply for historical reasons.
- That's not the same thing. A single result from old MBLD became a single result for new MBLD while in FMC (and BLD) three single results now form a completely new result.

Adding mean of 3 for BLD and FMC retroactively has no real comparison IMO. So, we need to come up with our own arguments for either side and I have to agree with @Sa967St here. None of the sides look particularly good.

**Comment by Divineskulls** [comment]
I'm not sure of etiquette on this site, so forgive me if I bump something for a bad reason.

The main reason I made an account on here is because of this tile rule. @iVinshe: There are plenty of "non-fast" people that use mf8 and mefferts tiles. I don't think it's a strictly "fast" thing. There is really no practical reason to ban these tiles. But that's not so much my issue right now. I think there should be some sort of announcement on the WCA site regarding the things that immediately effects competitors. I'm sure I'm not the only one who has a competition coming up and is unsure of the regulations'/Board's stance on these issues. Quick action is necessary.

**Comment by lgarron** [comment]
Thanks for making an account! The discussion here is open to anyone, as long as you try to be civil and productive.

To address your concern about an announcement: The [January 1 announcement](https://www.worldcubeassociation.org/2014-01-01) states the changes resulting in the current rules. Although a discussion about potential changes is taking place, there are currently no (permanent or temporary) decisions by the Board to make an exception. Unfortunately, the only current solution is to use a legally acceptable puzzle.

**Comment by lgarron** [comment]
I've marked the topics in the first post that have been handled.
Short remarks:
- Disallowing layover stickers for BLD events: This isn't particularly controversial, and will probably be considered in any overhaul of puzzle changes.
- DNS for pre-signing attempts won't change.

**Comment by lgarron** [comment]
Closing in favor of #172.
