### ISSUE TITLE
Mid-2014 Sprint

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#172]
This is for things that would be good to resolve before the yearly discussion for 2015 needs to start up.
I'll update this post as people commit to things.
- [ ] Example puzzle page (#168, @lgarron, @timhabermaas )
- [ ] Delegate voting (#169, @lgarron, @iVinshe )
  - First test: FMC Best of 3 (#150)
  - Second test: Recognizing retroactive records for BLD/FMC means (#170)
- [ ] Improve community-facing stuff/transparency (#174, @Sa967St)
- [ ] Finish the summarized changes for 2013 (#56, @Sa967St)
- [ ] Figure out puzzle changes, e.g. stickerless, pillowed, anything-goes (#173, @KitClement )
- [ ] Clean up web stuff (https://github.com/cubing/wca-documents-extra/issues/61, #134, @timhabermaas )
- [ ] Standardized puzzle covers (#67, @lgarron)
- [ ] Possible removal of feet solving (#175, @Sa967St)

This is in addition to [background roles](https://github.com/cubing/wca-documents/issues/149).
For a brief overview of future progress, see the [`mid-2014` milestone](https://github.com/cubing/wca-documents/issues?milestone=3) ("deadline": end of June).
