### ISSUE TITLE
WRC Discussion (May 17, 2015)

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-regulations#261]
See individual comments below (these were produced by @lgarron, @KitClement, @Sa967St during a Skype conversation).

TODO: Edit the posts below to reference the relevant GitHub issues.

List of the posts below:
- [x] #245 Extra scrambles for incidents that are not the competitor's fault (@lgarron)
- [x] #228 Extra attempts (@lgarron)
- [x] #263 Individual attempt DNS (@lgarron)
- [x] #203, #225 Allow disqualifying attempts when competitors waste time/resources (@Sa967St)
- [x] #251 Leniency for new competitors (@KitClement?)
- [x] #192 Sq-1 tabs (@KitClement)
- [x] #177 Stickerless Puzzles (@lgarron)
- [x] #262 Authority of the Board (@KitClement)
- [x] #235, #243 O-Rings (@lgarron)
- [x] #206, #218, #222, #230 Resetting timers (@lgarron)
- [x] #217 FMC Clocks (@KitClement)
- [x] #215 Not using the FMC sheet (@lgarron)
- [x] #214 Scramble Checking (@lgarron)
- [x] #213 Pyraminx Filtering (@lgarron)

Also, misc. small issues:
- [x] #260 A3c3+) Explicitly clarify that not resetting the timer is the judge's fault and results in a resolve (@lgarron)
- [x] #231 Hearing Aids/Wristwatches are Electronic (@lgarron)
- [x] #221 Clarify that only notation defined in Article 12 is acceptable for FMC. (@lgarron)
- [x] #253 A6b2) "delegate" is inconsistent with the rest of the Regs (@lgarron)
- [x] #246 Always use a space after comma in Square-1 notation (@lgarron)
- [x] #239 Regulation 9s and A1a are in conflict (@lgarron)

**Comment by lgarron** [comment]
## Extra scrambles for incidents that are not the competitor's fault (#245)
- If it's not the competitor's fault => extra attempt
- If it's unclear => give an extra attempt just in case, bring it up to the Board
  - count first attempt if possible, only count extra attempt if giving an extra attempt was the correct action

As with "not wasting time/resources" below, we rely on the Delegate's discretion to judge intention.

**Comment by lgarron** [comment]
## Extra attempts (#228)
- Extra attempts take place after all regular attempts are finished.
  - The extra attempt for a solve replaces the corresponding solve when the times are entered. 

> Another bizarre incident that occurred -- David Nguyen had a very interesting final average.  He had a timer malfunction on solve 1 (reset, timer still running and stops at low time like 0.05), so we awarded a new solve.  We ran out of scorecards, so we were using makeshift ones written on extra paper.  The scrambler, Chris Braiedy, next gave scramble 2 and added a line at the bottom of the scorecard for E1.  The judge, however, thought E1 was being given already, and wrote the time in the E1 box.  Chris Braiedy corrected this by drawing an arrow  from E1 to the box for scramble 2.  He then gave scramble 3.  The judge in this case made another error, writing the box in the empty scramble 2 box, which only had an arrow pointing to it.  Chris clearly gave scramble 3 again based on this scorecard, as it was the next open line on the card.   David reported a repeated scramble, which caused a lot of craziness and confusion -- all of which was sorted out.  We fixed the scorecard to reflect the correct time for scramble 3, and proceeded to give him scramble 4, then 5, then E1.  (He actually had the exact same timer malfunction happen later, so he actually replaced 5 with E2) (https://groups.google.com/forum/#!msg/wca-delegates/8y52PNr_jTM/jpA_I8NGgeYJ)(Minnesota Cube Melt 2015)

**Comment by lgarron** [comment]
## Individual attempt DNS (#263)

3a1) Competitors must be present and ready to compete when they are called to compete for an attempt. Penalty: disqualification from the event. Alternatively, a competitor who is not present in time for an individually scheduled attempt (e.g. an FMC attempt, a Multiple Blindfolded attempt) may be considered to have declined that attempt (DNS), at the discretion of the WCA Delegate.

(from [this discussion](https://groups.google.com/d/msgid/wca-delegates/CAF2SvPVD28J1HEH5MRtyEFEhP3%3Dky%2BPJjcnJfG5j7ogz78axTQ%40mail.gmail.com?utm_medium=email&utm_source=footer))

**Comment by lgarron** [comment]
## Allow disqualifying attempts when competitors waste time/resources (#203, #225)
- If the competitor does something that wastes time or resources (because they're being silly, not e.g. because they're not fast at an event), the Delegate may disqualify them from the relevant attempts/events.

TODO(@Sa967St): think of a better way to word this. Consider including (quite a few) concrete examples based on past incidents. Possibly also examples of things that are not really wasting time (e.g. just being slow).

Examples:
- Intentional +16 penalties
- Intentionally poor FMC results (can waste solution checker time)
- Intentionally letting timer run to get poor results
- Solving a puzzle that the competitor does not know how to solve

Non-examples:
- Competitors who aren't fast at a puzzle, but are trying their best.
- Competitors who aren't good at FMC, but still taking it seriously.

From [Chris Krueger](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wca-delegates/Y5LtG-9u4fk%5B76-100%5D):

> This discussion came up again among some of us today, so I want to again suggest a regulation change about allowing disqualification from a solve/event at delegate discretion for a competitor not competing in good faith. Currently, I could walk into a competition without pre-announced cutoff times and announce that I intend to complete every solve in 9:59.99, and under a strict reading of the current regulations no one could do anything about it. I'd like to change that. 
> 
> Change the wording of A1c to 
> A competitor participating in an event must be able to fulfill the event's requirements (e.g. know how to solve the puzzle within a given time limit). A competitor competing with expectation of a DNF result or intentionally poor result may be disqualified from the solve or the event, at the discretion of the WCA Delegate.
> Restore E1 to read 
> Article A1c applies to Fewest Moves Solving. 
> 
> A justification based on wasting competition resources can be read from 2J 2K and A1c. The proposed change just simplifies that.

**Comment by lgarron** [comment]
## Leniency for new competitors (#251)
- Applies only to new competitors
  - Possible Guideline: may also include competitors who haven't competed in a while, and accidentally follow old Regulations
  - This is about experience more than knowing the Regulations (i.e. competitors who've competed before should definitely be experienced)
- At the Delegate's discretion, an incident caused by a new competitor's inexperience (e.g. not waiting for the green light, holding on to the puzzle while stopping the timer, karate chopping the timer, going over inspection time due to misunderstanding how to start an attempt, procedural time penalties) may be replaced with an extra attempt
  - It would _not_ be okay to waive individual penalties (unless the Regulation explicitly allows so). A full extra attempt should be given.

**Comment by lgarron** [comment]
## Sq-1 tabs (#192)
- Organizers may enforce the use of tabs (for alignment) after scrambling, where competitors (and not the judge) remove the tabs during inspection.

Plan: propose this to the Board as-is, else consider it for later Regulations, with possible Delegate voting.

This is the biggest problem in #192 (except intentional turns from #196).

**Comment by lgarron** [comment]
## Stickerless Puzzles (#177)

See this [draft commit](https://github.com/cubing/wca-documents/commit/329e6bfdd4d91038d13c5777c49d93c9a2141103).

Plan: propose the draft commit to the Board (with no other puzzle changes), since this is the most anticipated puzzle change, and has been publicly promised-ish.
(If the Board says no, then no puzzle changes.)

**Comment by KitClement** [comment]
## Authority of the Board (#262)

See #262

**Comment by lgarron** [comment]
## O-Rings (#235, #243)

Add an official recommendation ("should", but not yet "must") for the following timer modifications:
- O-rings
- padded battery compartment

**Comment by lgarron** [comment]
## Resetting timers (#206, #218, #222, #230)

If the competitor resets the timer before the end of the attempt => DNF
However, a +2 time penalty may be given instead if the result has been completely written down, at the judge's discretion.

**Comment by KitClement** [comment]
## FMC Clocks (#217)
- Competitors may use clocks that don't have any additional features that would allow the competitor to cheat, at the discretion/approval of the judge.

**Comment by lgarron** [comment]
## Not using the FMC sheet (#215)

Clarify that solutions written on a different piece of paper are okay, as long as a single move sequence is unambiguously indicated as the submitted solution.

Possible clarification: no words, arrows, complicated direction, etc.

**Comment by lgarron** [comment]
## Scramble Checking (#214)

The organization team may require scramblers to take additional measures to make sure that they are performing the correct scrambles (e.g. signing the score sheet to affirm that they performed the correctly-numbered scramble and checked that it matches the image).

**Comment by KitClement** [comment]
## Pyraminx Filtering (#213)

It has long been promised that the WRC would change the scramble filter to 6 moves.

**Comment by Claster** [comment]
> Extra attempts take place after all regular attempts are finished.

Is it mandatory? Why not immediately after the solve that is replaced?

**Comment by lgarron** [comment]
Yes, the idea is to make this way of doing it mandatory, in order
standardize it. The order of handling extra attempts has led to confusion
in competitions in the past.

This is still in a draft branch; we'll see if the Board also considers it
uncontroversial enough.
