### ISSUE TITLE
Issues for the 2016 Regulations change

### ISSUE THREAD

**Issue by Laura-O** [thewca/wca-regulations#326]
I want to start a collection of issues for the upcoming regulation change. Everyone feel free to add something or assign yourself.
(Disclaimer: this list is not necessarily a complete list of upcoming regulation changes)

**List of issues:**
- [x] clarify the removal of tabs used in SQ-1 #315 (@Claster)
- [x] changes in Z4  #311 and #325 (@Laura-O)
- [x] Clarify 3d #312
- [x] Cumulative time limits for more than one event #296 (@Laura-O)
- [x] Use of scrambles on more than one consecutive day #295 (@Laura-O)
- [x] Clock pin caps #189
- [x] Clarify that FMC judges may also be FMC competitors #165
- [x] Clarify sticker requirements for FMC (not only coloured stickers) #68
- [x] Clarify that any part of the body is permitted, by default #300  (@Claster)
- [x] Definition or recommendation for the size of mats #304 
- [x] Add next Pro Timer generation #333
- [x] Number of advancing competitors #314 
- [ ] Include something about propaganda #330 
- [x] TNoodle update
- [x] Clarification of FMC regulations (E2e)
- [x] Results for rounds with cumulative time limit #303

**Current polls:**
- [x] Exception for pillowed 7x7x7 #124 (will not be changed)
- [x] Move limit for FMC #203 (will not be changed)
- [x] Do extra attempts right after they were granted #228, #341 

I didn't include any small fixes and corrections, I think it's OK to do those changes without keeping track of them (and we have the commit history :wink: ).

**Comment by viroulep** [comment]
FYI I've updated the checklist and moved the "extra attempts" issue to the current polls list.
